### ISSUE TITLE
Hello yattabyte

### ISSUE THREAD

**Issue by rzeronte** [Yattabyte/Delta#86]
I was working a few weeks in skeletal animation, and i have problem with some triangles in transformations. 

we could contact via email, to see if you can help me?, the code is similar ... both taken from the famous tutorial38 of "ogldev":

Some models it works fine:
![skeletal_animation](https://user-images.githubusercontent.com/7849348/77856069-e9ff4100-71f4-11ea-8b31-e97e5a0e13af.gif)

![bad_transforms_hand](https://user-images.githubusercontent.com/7849348/77856083-f8e5f380-71f4-11ea-91b3-702931e7a4d7.gif)

Here is my code: https://github.com/rzeronte/brakeza3d/blob/master/headers/Objects/Mesh3DAnimated.cpp

**Comment by Yattabyte** [comment]
I've closed this issue for the following reasons:
 - This ticket does not describe the issue nor steps to reproduce it
 - This ticket does not belong to this project

I get your need for help, but if you're going to open an issue on another project just to seek help, at least describe the problem better (gifs of the best case scenario don't help)
